FROM docker-0.unsee.tech/ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Asia/Shanghai \
    LC_ALL=C.UTF-8

RUN apt update \
    && apt install -y \
    software-properties-common ca-certificates \
    libncurses5 libaio1 libmecab2 libncurses5 libaio1 libmecab2 \
    perl-modules-5.34 libdbd-mysql-perl libdbi-perl libdevel-checklib-perl \
    supervisor openssh-server wget apt-utils apparmor

# 安装PHP5.6和相关扩展
RUN LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php \
    && apt update \
    && apt install -y \
    php5.6 \
    php5.6-fpm \
    php5.6-common \
    php5.6-mysql \
    php5.6-gd \
    php5.6-mbstring \
    php5.6-curl \
    php5.6-soap \
    php5.6-json \
    php5.6-xml \
    php5.6-apcu \
    php5.6-mcrypt \
    php5.6-cgi \
    php5.6-dev \
    apache2 \
    libapache2-mod-php5.6

COPY mysql.cnf /tmp
COPY init.sql /tmp
RUN cd /opt \
    && wget https://cdn.mysql.com/archives/mysql-5.7/mysql-server_5.7.34-1ubuntu18.04_amd64.deb-bundle.tar \
    && tar -xvf mysql-server*.tar -C /opt \
    && rm mysql-server_*.deb-bundle.tar \
    && rm mysql-test*.deb && rm mysql-community-test*.deb \
    && dpkg -i *.deb || true \
    && apt install -f -y \
    && rm -rf *.deb \
    && mv /tmp/mysql.cnf /etc/mysql/mysql.cnf \
    && chmod 644 /etc/mysql/mysql.cnf \
    && (mysqld_safe &) \
    && sleep 5 \
    && mysql -uroot -proot -e "SOURCE /tmp/init.sql;" \
    && rm /tmp/init.sql

# 配置 Supervisor
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# 配置 SSH
RUN echo 'root:p@ss1234' | chpasswd \
    && sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config \
    && sed -i 's/UsePAM yes/UsePAM no/' /etc/ssh/sshd_config \
    && sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config \
    && ssh-keygen -A \
    && mkdir -p  /var/run/sshd

EXPOSE 3306

CMD ["/usr/bin/supervisord", "-n"]